"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import config
import cloudinary


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY in the environment on Render (and never commit real secrets).
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-ajznvh!hvi)c9+p%0mp*f8q$e-477b=_3v$yzl$m!^^)-8uj4#',
)

# Set DEBUG=False in production (e.g. Render). Defaults to True for local dev without .env.
DEBUG = config('DEBUG', default=True, cast=bool)

# Comma-separated hosts, or * alone (dev only — e.g. HTTPS tunnels like ngrok change hostname each run).
_allowed_raw = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').strip()
if _allowed_raw == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_raw.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Local apps
    'users',
    'assistant',
    'emotions',
    'recommendations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# We use a single NEON_DATABASE_URL connection string (from Neon PostgreSQL)
# defined in backend/.env, for example:
#   NEON_DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DBNAME?sslmode=require
#
# If NEON_DATABASE_URL is not set, we fall back to local SQLite (dev only).

NEON_DATABASE_URL = config("NEON_DATABASE_URL", default="")

# Database configuration
# If NEON_DATABASE_URL is set, use PostgreSQL (Neon)
# Otherwise, fall back to SQLite for local development
# 
# To use SQLite temporarily (if Neon connection fails):
# 1. Comment out or remove NEON_DATABASE_URL from your .env file
# 2. Or set it to empty: NEON_DATABASE_URL=
if NEON_DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            NEON_DATABASE_URL,
            conn_max_age=300,
            conn_health_checks=True,
        )
    }
else:
    # Fall back to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cloudinary configuration (for profile pictures and other media)
CLOUDINARY_CLOUD_NAME = config("CLOUDINARY_CLOUD_NAME", default="")
CLOUDINARY_API_KEY = config("CLOUDINARY_API_KEY", default="")
CLOUDINARY_API_SECRET = config("CLOUDINARY_API_SECRET", default="")

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Optional: e.g. http://192.168.1.10:3000 (same origin you open on the phone)
_cors_extra = config('CORS_ALLOWED_ORIGINS_EXTRA', default='')
if _cors_extra.strip():
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _cors_extra.split(',') if o.strip()]

# In DEBUG, allow typical LAN dev URLs and HTTPS tunnels (ngrok / Cloudflare) for mobile camera testing
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://(192\.168\.\d{1,3}\.\d{1,3}|10\.\d{1,3}\.\d{1,3}\.\d{1,3})(:\d+)?$',
        r'^https://[a-zA-Z0-9-]+\.ngrok-free\.app$',
        r'^https://[a-zA-Z0-9-]+\.ngrok\.io$',
        r'^https://[a-zA-Z0-9-]+\.ngrok-free\.dev$',
        r'^https://[a-zA-Z0-9-]+\.trycloudflare\.com$',
        r'^https://[a-zA-Z0-9-]+\.loca\.lt$',
    ]

CORS_ALLOW_CREDENTIALS = True

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Emotion Detection Microservice Settings
EMOTION_MICROSERVICE_URL = config('EMOTION_MICROSERVICE_URL', default='http://localhost:8001')
# 7-Class Emotion Detection Microservice (new service with better accuracy)
EMOTION_7CLASS_MICROSERVICE_URL = config('EMOTION_7CLASS_MICROSERVICE_URL', default='http://localhost:5002')

# Recommendation Microservice Settings
RECOMMENDATION_MICROSERVICE_URL = config('RECOMMENDATION_MICROSERVICE_URL', default='http://localhost:5000/api')
TEXT_EMOTION_MICROSERVICE_URL = config('TEXT_EMOTION_MICROSERVICE_URL', default='http://localhost:5001')
# Audio / voice emotion (Wav2Vec2) microservice
VOICE_EMOTION_MICROSERVICE_URL = config('VOICE_EMOTION_MICROSERVICE_URL', default='http://127.0.0.1:5003')

# Frontend base URL (links in emails / push payloads)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Email (SendGrid via SMTP — use SENDGRID_API_KEY + verified sender)
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL', default='')
DEFAULT_FROM_EMAIL = (
    config('DEFAULT_FROM_EMAIL', default='').strip()
    or SENDGRID_FROM_EMAIL
    or 'EmotionAI <no-reply@localhost>'
)
if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
else:
    EMAIL_BACKEND = config(
        'EMAIL_BACKEND',
        default='django.core.mail.backends.console.EmailBackend',
    )

# Web Push (VAPID) — generate with: pywebpush.vapid._get_vapid_keys() or openssl
WEB_PUSH_PUBLIC_KEY = config('WEB_PUSH_PUBLIC_KEY', default='')
WEB_PUSH_PRIVATE_KEY = config('WEB_PUSH_PRIVATE_KEY', default='')
WEB_PUSH_ADMIN_CONTACT = config('WEB_PUSH_ADMIN_CONTACT', default='mailto:support@example.com')
