# Generated by Django 5.1.3 on 2026-03-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy 😊'), ('sad', 'Sad 😢'), ('angry', 'Angry 😠'), ('anxious', 'Anxious 😰'), ('neutral', 'Neutral 😐'), ('tired', 'Tired 😴'), ('excited', 'Excited 🎉'), ('loved', 'Loved 😍')], max_length=20)),
                ('intensity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Mood Log',
                'verbose_name_plural': 'Quick Mood Logs',
                'db_table': 'quick_mood_logs',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('facial', 'Facial Expression'), ('fused', 'Multimodal Fusion')], max_length=10)),
                ('happy', models.FloatField(default=0.0)),
                ('sad', models.FloatField(default=0.0)),
                ('angry', models.FloatField(default=0.0)),
                ('anxious', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('surprised', models.FloatField(default=0.0)),
                ('disgusted', models.FloatField(default=0.0)),
                ('fearful', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0, help_text='Negative (-1) to Positive (+1)')),
                ('arousal', models.FloatField(default=0.0, help_text='Low (0) to High (1)')),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_detections', to='assistant.checkinentry')),
            ],
            options={
                'verbose_name': 'Emotion Detection',
                'verbose_name_plural': 'Emotion Detections',
                'db_table': 'emotion_detections',
                'ordering': ['-detected_at'],
            },
        ),
    ]
