# Generated by Django 5.1.3 on 2025-12-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy 😊'), ('sad', 'Sad 😢'), ('angry', 'Angry 😠'), ('anxious', 'Anxious 😰'), ('neutral', 'Neutral 😐'), ('tired', 'Tired 😴'), ('excited', 'Excited 🎉'), ('loved', 'Loved 😍')], max_length=20)),
                ('intensity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Mood Log',
                'verbose_name_plural': 'Quick Mood Logs',
                'db_table': 'quick_mood_logs',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.DeleteModel(
            name='MoodCheckIn',
        ),
    ]
