# Generated by Django 5.1.3 on 2025-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ImageField(upload_to='entry_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Media',
                'verbose_name_plural': 'Entry Media',
                'db_table': 'entry_media',
            },
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Tag',
                'verbose_name_plural': 'Entry Tags',
                'db_table': 'entry_tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntryTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Tag Relation',
                'verbose_name_plural': 'Entry Tag Relations',
                'db_table': 'entry_tag_relations',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text_content', models.TextField(blank=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_entries/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_entries/')),
                ('transcription', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds for voice/video')),
                ('privacy_setting', models.CharField(choices=[('private', 'Private'), ('therapist', 'Shared with Therapist')], default='private', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('entry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
