# Generated by Django 5.1.3 on 2025-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='emotion',
            field=models.CharField(blank=True, help_text='User-selected emotion', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotion_confidence',
            field=models.FloatField(blank=True, help_text='ML confidence score (0-1)', null=True),
        ),
    ]
