# Generated by Django 5.1.3 on 2025-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_emotion_journalentry_emotion_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='text_content_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted text content'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='title_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted title'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transcription_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted transcription'),
        ),
    ]
