# Generated by Django 5.1.3 on 2025-12-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_add_encrypted_fields_to_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='transcription',
        ),
    ]
