# Generated by Django 5.1.3 on 2025-12-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_plain_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='video_file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for video file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='voice_file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for voice file', max_length=500, null=True),
        ),
    ]
