# Generated by Django 5.1.3 on 2026-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message_encrypted', models.TextField(blank=True, help_text='Encrypted message')),
                ('entry_reference_id', models.IntegerField(blank=True, null=True)),
                ('emotion_context_encrypted', models.TextField(blank=True, help_text='Encrypted emotion context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('mood_insight', 'Mood Insight'), ('weekly_report', 'Weekly Report'), ('streak_alert', 'Streak Alert'), ('ai_suggestion', 'AI Suggestion'), ('recommendation', 'Recommendation'), ('system', 'System Notification')], max_length=30)),
                ('title_encrypted', models.TextField(blank=True, help_text='Encrypted title')),
                ('message_encrypted', models.TextField(blank=True, help_text='Encrypted message')),
                ('metadata_encrypted', models.TextField(blank=True, help_text='Encrypted metadata')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (entry, recommendation, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_encrypted', models.TextField(blank=True, help_text='Encrypted title')),
                ('description_encrypted', models.TextField(blank=True, help_text='Encrypted description')),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation'), ('social', 'Social Activity'), ('creative', 'Creative Activity'), ('rest', 'Rest & Relaxation'), ('therapy', 'Professional Support'), ('self_expression', 'Journaling & Self-Expression'), ('other', 'Other')], default='other', max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(blank=True, help_text='What triggered this recommendation', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Recommendation',
                'verbose_name_plural': 'User Recommendations',
                'db_table': 'user_recommendations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
