# Generated by Django 5.1.3 on 2025-12-06 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecommendation',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'User Recommendation', 'verbose_name_plural': 'User Recommendations'},
        ),
        migrations.RenameField(
            model_name='userrecommendation',
            old_name='recommended_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userrecommendation',
            old_name='is_bookmarked',
            new_name='is_dismissed',
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aichatmessage',
            name='entry_reference',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='target_emotions',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='entry_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='triggered_by',
            field=models.CharField(blank=True, help_text='What triggered this recommendation', max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation'), ('social', 'Social Activity'), ('creative', 'Creative Activity'), ('rest', 'Rest & Relaxation'), ('therapy', 'Professional Support'), ('journaling', 'Journaling'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='times_completed',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('mood_insight', 'Mood Insight'), ('weekly_report', 'Weekly Report'), ('streak_alert', 'Streak Alert'), ('ai_suggestion', 'AI Suggestion'), ('recommendation', 'Recommendation'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (entry, recommendation, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
