# Generated by Django 5.1.3 on 2025-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_userrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='emotion_context_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted emotion context'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='message_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted metadata'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted title'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted description'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted title'),
        ),
    ]
