# Generated by Django 5.1.3 on 2026-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video')], default='text', max_length=10)),
                ('title_encrypted', models.TextField(blank=True, help_text='Encrypted title')),
                ('text_content_encrypted', models.TextField(blank=True, help_text='Encrypted text content')),
                ('transcription_encrypted', models.TextField(blank=True, help_text='Encrypted transcription')),
                ('voice_file', models.URLField(blank=True, help_text='Cloudinary URL for voice file', max_length=500, null=True)),
                ('video_file', models.URLField(blank=True, help_text='Cloudinary URL for video file', max_length=500, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds for voice/video')),
                ('privacy_setting', models.CharField(choices=[('private', 'Private'), ('therapist', 'Shared with Therapist')], default='private', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('entry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('emotion', models.CharField(blank=True, help_text='User-selected emotion', max_length=50)),
                ('emotion_confidence', models.FloatField(blank=True, help_text='ML confidence score (0-1)', null=True)),
            ],
            options={
                'verbose_name': 'Check-In Entry',
                'verbose_name_plural': 'Check-In Entries',
                'db_table': 'checkin_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='EntryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ImageField(upload_to='entry_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Media',
                'verbose_name_plural': 'Entry Media',
                'db_table': 'entry_media',
            },
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Tag',
                'verbose_name_plural': 'Entry Tags',
                'db_table': 'entry_tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntryTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entry Tag Relation',
                'verbose_name_plural': 'Entry Tag Relations',
                'db_table': 'entry_tag_relations',
            },
        ),
    ]
