# Generated by Django 5.1.3 on 2025-11-26 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted phone number'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_settings', models.TextField(blank=True, help_text='Encrypted JSON')),
                ('privacy_settings', models.TextField(blank=True, help_text='Encrypted JSON')),
                ('appearance_settings', models.TextField(blank=True, help_text='Encrypted JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
