# Generated by Django 5.1.3 on 2025-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_encrypted_user_phone_number_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='onboarding_settings',
            field=models.TextField(blank=True, help_text='Encrypted JSON - storage preference and feature permissions'),
        ),
    ]
