# Generated by Django 5.1.3 on 2025-12-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_onboarding_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='journaling_goals',
            new_name='mood_tracking_goals',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='preferred_journal_time',
            new_name='preferred_checkin_time',
        ),
    ]
