# Generated by Django 5.1.3 on 2026-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_journaling_goals_user_mood_tracking_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='recommendation_settings',
            field=models.TextField(blank=True, help_text='Encrypted JSON - music, exercise, content preferences'),
        ),
    ]
